import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const DEFAULT_DIMENSION = 1024;

const rawArg = process.argv[2];
const rawEnv = process.env.EMBEDDING_DIMENSION;
const rawValue = rawArg ?? rawEnv;

const parseDimension = (value) => {
  if (!value) return undefined;
  const parsed = Number(value);
  if (!Number.isFinite(parsed) || parsed <= 0) return undefined;
  return Math.floor(parsed);
};

const dimension = parseDimension(rawValue) ?? DEFAULT_DIMENSION;

const scriptDir = dirname(fileURLToPath(import.meta.url));
const targetPath = join(scriptDir, '..', 'convex', 'util', 'embeddingDimension.ts');

const content = `// Generated by scripts/set_embedding_dimension.mjs\n` +
  `// Update via: EMBEDDING_DIMENSION=1536 node scripts/set_embedding_dimension.mjs\n` +
  `export const EMBEDDING_DIMENSION: number = ${dimension};\n`;

await writeFile(targetPath, content, 'utf8');
